<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/**
 * Rm_soap_embed — Standalone SOAP viewer for embedding via iframe.
 *
 * Access is NOT protected by CI session. Instead it uses a short-lived
 * HMAC-signed token generated by the API endpoint getSoapLink.
 *
 * URL:  rekam_medis/Rm_soap_embed/view?nomr={no_mr}&st={signed_token}
 */
class Rm_soap_embed extends MX_Controller {

    function __construct() {
        parent::__construct();
        // Load config for token secret (same as API service)
        $this->load->config('api_service');
        $this->load->model('Rm_soap_model', 'Rm_soap');
        $this->output->enable_profiler(false);
    }

    // -------------------------------------------------------------------------
    // PUBLIC ENDPOINTS
    // -------------------------------------------------------------------------

    public function view() {

        $nomr  = trim((string) $this->input->get('nomr'));
        $token = trim((string) $this->input->get('st'));
        $style = trim((string) $this->input->get('style'));

        // Validate signed token
        $validation = $this->_validateEmbedToken($token, $nomr);
        if ($validation['valid'] === false) {
            $this->_showError($validation['message'], $nomr);
            return;
        }

        // Fetch patient header
        $pasien = $this->db->get_where('mt_master_pasien', ['no_mr' => $nomr])->row();
        if (!$pasien) {
            $this->_showError('Data pasien tidak ditemukan untuk No. MR: ' . htmlspecialchars($nomr), $nomr);
            return;
        }

        // Fetch SOAP records
        $records = $this->Rm_soap->get_by_nomr($nomr, 100);

        // Batch-fetch related data
        $kunjungan_ids  = [];
        $registrasi_ids = [];
        foreach ($records as $_item) {
            if (!empty($_item->no_kunjungan))  $kunjungan_ids[$_item->no_kunjungan]   = $_item->no_kunjungan;
            if (!empty($_item->no_registrasi)) $registrasi_ids[$_item->no_registrasi] = $_item->no_registrasi;
        }

        $map_eresep    = $this->Rm_soap->get_eresep_by_kunjungan(array_values($kunjungan_ids));
        $map_emr       = $this->Rm_soap->get_emr_files_by_kunjungan(array_values($registrasi_ids));
        $map_penunjang = $this->Rm_soap->get_penunjang_by_kunjungan(array_values($registrasi_ids));

        $data = [
            'pasien'        => $pasien,
            'records'       => $records,
            'map_eresep'    => $map_eresep,
            'map_emr'       => $map_emr,
            'map_penunjang' => $map_penunjang,
            'nomr'          => $nomr,
            'token'         => $token,
            'expires_at'    => $validation['expires_at'],
        ];

        if(isset($style) && $style === 'table') {
            // Minimal style for tight embedding (e.g. mobile app)
            $this->load->view('Rm_soap/embed_view_style_table', $data);
        }else{
            // Standalone page — do NOT use the main layout
            $this->load->view('Rm_soap/embed_view', $data);
        }

        
    }

    // -------------------------------------------------------------------------
    // PRIVATE HELPERS
    // -------------------------------------------------------------------------

    /**
     * Validate a signed embed token for the given no_mr.
     *
     * @param  string $token
     * @param  string $nomr
     * @return array  ['valid' => bool, 'message' => string, 'expires_at' => int|null]
     */
    private function _validateEmbedToken($token, $nomr) {

        if (empty($token) || empty($nomr)) {
            return ['valid' => false, 'message' => 'Parameter tidak lengkap.', 'expires_at' => null];
        }

        $parts = explode('.', $token, 2);
        if (count($parts) !== 2) {
            return ['valid' => false, 'message' => 'Format token tidak valid.', 'expires_at' => null];
        }

        $decoded = base64_decode($parts[0], true);
        if ($decoded === false) {
            return ['valid' => false, 'message' => 'Token tidak dapat didekode.', 'expires_at' => null];
        }

        $inner = explode('|', $decoded, 2);
        if (count($inner) !== 2) {
            return ['valid' => false, 'message' => 'Payload token tidak valid.', 'expires_at' => null];
        }

        list($token_nomr, $expire) = $inner;
        $expire = (int) $expire;

        // Verify no_mr matches
        if ($token_nomr !== $nomr) {
            return ['valid' => false, 'message' => 'Token tidak sesuai dengan No. MR.', 'expires_at' => null];
        }

        // Verify HMAC signature (constant-time)
        $secret   = $this->config->item('api_token_secret');
        $expected = hash_hmac('sha256', $decoded, $secret);
        if (!hash_equals($expected, $parts[1])) {
            return ['valid' => false, 'message' => 'Tanda tangan token tidak valid.', 'expires_at' => null];
        }

        // Check expiry AFTER signature verification (prevent oracle attacks)
        if (time() > $expire) {
            return ['valid' => false, 'message' => 'Sesi telah habis. Silakan minta link baru dari aplikasi.', 'expires_at' => $expire];
        }

        return ['valid' => true, 'message' => 'OK', 'expires_at' => $expire];
    }

    /**
     * Render the standalone error/expired page.
     */
    private function _showError($message, $nomr = '') {
        $this->load->view('Rm_soap/embed_error', [
            'message' => $message,
            'nomr'    => $nomr,
        ]);
    }
}

/* End of file Rm_soap_embed.php */
/* Location: ./application/modules/rekam_medis/controllers/Rm_soap_embed.php */
