<div style="text-align: center;"><b>ECHOCARDIOGRAPHY</b></div>
<div style="text-align: center;"><b><br></b></div>
<div style="text-align: left;">Keterangan Klinis / Indikasi :</div>
<div style="text-align: left;"><br></div>
<div style="text-align: left;"><b>2D : Parasternal View :</b></div>
<div style="text-align: left;"><br></div>
<div style="text-align: left;"><b>&nbsp; &nbsp; &nbsp; &nbsp; Apical View :</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>&nbsp; &nbsp; &nbsp; &nbsp; Subcostal View :</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>&nbsp; &nbsp; &nbsp; &nbsp; Supra Sternal View :</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>M. Mode :</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>Color Doppler :</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>Doppler :&nbsp;</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>Kesimpulan :</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>M. Mode :&nbsp;</b></div>
<div style="text-align: left;"><b>Angka normal dewasa (angka normal diambil dari buku : Practical Echocardiography J. Roelandt 1977B) </b>Aorta Root diameter (20 - 37 mm) ; Aocusp separation (15 - 26 mm) ; Valve cusp motion/other ; L.A Dimension (15 - 40 m) LA/Ao Ratio (&lt; 1,3) ; RV Dimension (&lt; 30 mm) ; L.V. EDD (&lt; 56 mm) ; ESD (Variable) ; RF (53 - 77 %) ; FS (&gt; 25%) ; Mean VCF ; LVPW thickness (ED) (6 - 12 mm) ; Amplitude (6 - 12 mm) motion pattern N/hyper/hypo paradoxical % thickening (30%) ; IVS thickness (ED) (6 - 12 mm) ; Amplitude (5 - 10 mm) motion pattern N/hypher/hypo paradoxical % thickening (&gt; 30%) ; IVS/LVPW Ratio (&lt; 1,3) ; Mitral Valve Anterior leaflet : DE amplitude diastolic motion (&gt; 20 mm) ; EF slope N/MS/AI/equivocal (&gt; 75 mm/sec) ; Systolic motion (N/SM/Prolapse/equivocal) ; Pericardial effusion : non/small/moderate/Large</div>