<div style="text-align: center;"><b>HASIL PEMERIKSAAN DIAGNOSTIK NON INVASIF VASKULER</b></div>
<div style="text-align: left;"><br><b>Pada pemeriksaan duplex sonography femoralis didapatkan :</b></div>
<div style="text-align: center;"><br></div>
<div style="text-align: left;"><b>Arteri</b> :</div>
<div style="text-align: left;"><br>-	Gambaran anatomi pembuluh darah arteri femoralis communis, arteri poplitea, arteri tibialis anterior-posterior, arteri dorsalis pedis bilateral rata dan tidak menebal</div>
<div style="text-align: left;"><br>-	Arteri femoralis communis, arteri poplitea, arteri tibialis anterior-posterior, arteri dorsalis pedis bilateral morfologi kurva Doppler triphasic</div>
<div style="text-align: left;"><br>-	Colour coded mengisi penuh lumen pembuluh darah arteri femoralis communis, arteri poplitea, arteri tibialis anterior-posterior, arteri dorsalis pedis bilateral</div>
<div style="text-align: left;"><b>Vena</b> :</div>
<div style="text-align: left;"><br>-	Compressi Ultrasound (CUS) negative pada vena femoralis, vena poplitea bilateral</div>
<div style="text-align: left;"><br>-	Augmentasi (+) dengan uji squeeze distal pada vena femoralis, vena poplitea bilateral</div>
<div style="text-align: left;"><br>-	Reflux (-) pada kedua tungkai </div>
<div style="text-align: left;"><br>-	Diameter GSV sinistra proximal mm, mid mm, distal mm</div>
<div style="text-align: left;"><br>-	Diameter GSV dextra proximal mm, mid mm, distal mm</div>
<div style="text-align: left;"><b>Kesimpulan</b> :</div>
<div style="text-align: left;"><br>-	Normal flow arteri pada kedua tungkai</div>
<div style="text-align: left;"><br>-	CVI (-) pada kedua tungkai</div>
<div style="text-align: left;"><br>-	DVT (-) pada kedua tungkai</div>