<div style="text-align: center;" font-size:="" 18px;=""><b>LAPORAN TINDAKAN ESWL</b></div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>Tanggal Tindakan&nbsp;</b>:&nbsp;</div>
<div style="text-align: left;"><br></div>
<div style="text-align: left;"><b>Jam Tindakan&nbsp;</b>:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; s/d</div>
<div style="text-align: left;"><br></div>
<div style="text-align: left;"><b>Diagnosa Pra Bedah </b>&nbsp;: &nbsp;</div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>Diagnosa Pasca Bedah </b>&nbsp;: &nbsp;</div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>Tindakan </b>&nbsp;: &nbsp;</div>
<div style="text-align: left;"><b><br></b></div>
<div style="text-align: left;"><b>Komplikasi </b>&nbsp;: &nbsp;</div>
<div style="text-align: left;"><br></div>
<div style="text-align: center;"><b>PROSEDUR TINDAKAN</b></div>
<div style="text-align: left;"><br></div>
<div style="text-align: left;">-</div>
<div style="text-align: left;">-</div>
<div style="text-align: left;">-</div>
<div style="text-align: left;">-</div>