<style>
.body{
  font-family: Arial, Helvetica, sans-serif;
  color: black;
  text-align: left;
  background-color: white; 
  border-spacing: 5em;
}

.monotype_style{
    font-family : Monotype Corsiva, Times, Serif !important;
}

</style>

<div class="body">
  <table width="100%" border="0">
    <tr>
      <td width="10%"><img src="<?php echo base_url().COMP_ICON?>" alt="" width="70px"></td>
      <td align="left" width="90%">
        <span><b>INSTALASI FARMASI</b></span><br>
        <span><?php echo strtoupper(COMP_LONG); ?></span><br>
        <span><?php echo COMP_ADDRESS_SORT; ?></span>
      </td>
    </tr>
  </table> 
  <hr>
  <br>
  <p style="float: right; font-weight: bold;">SALINAN RESEP</p><br>
  <table style="width: 100%">
    <tr>
      <td width="20%">No.</td>
      <td>: <?php echo $result->kode_trans_far; ?></td>
      <td width="20%">Tgl.</td>
      <td>: <?php echo $this->tanggal->formatDatedmY($result->tgl_trans); ?></td>
    </tr>
    <tr>
      <td width="20%">Dari Dokter</td>
      <td colspan="3">: <?php echo $result->dokter_pengirim; ?></td>
    </tr>
    <tr>
      <td width="20%">Poli/Klinik</td>
      <td colspan="2">: <?php echo $result->nama_bagian; ?></td>
    </tr>
  </table>
    
  <div style="min-height: 500px !important; vertical-align: top">
    <?php echo $result->copy_resep_text; ?>
  </div>

  <table>
    <tr>
      <td width="20%">Nama Pasien</td>
      <td>: <?php echo ucwords(strtolower($result->nama_pasien)); ?></td>
    </tr>
    <tr>
      <td width="20%">Umur</td>
      <td>: <?php echo $this->tanggal->AgeWithYearMonthDay($result->tgl_lhr)?></td>
    </tr>
    <tr>
      <td width="20%">Alamat</td>
      <td>: <?php echo ucwords(strtolower($result->almt_ttp_pasien)); ?></td>
    </tr>
  </table>
  <hr>
  <span style="font-style: italic">a copy of this recipe is generated by the system.</span>
</div>

